name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/node.js.yml@4997804869780080c055303a9a2f0278423e343d
