name: Node.js CI

on:
  push:
    paths:
      - '.github/workflows/node.js.yml'
      - 'src/**'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/node.js.yml'
      - 'src/**'
      - 'Dockerfile'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/docker-build.yml@b486a6c7e9cae1c1bb685b70f9d8075e59ae3287
