name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/node.js.yml'
      - 'src/**'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/node.js.yml'
      - 'src/**'
      - 'Dockerfile'
  workflow_dispatch:

permisions:
  contents: read

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/docker-build.yml@65ae9efd118a117d6dc3e6bda5d1332d11de1cc8
