name: Node.js CI

on:
  push:
    paths:
      - '.github/workflows/node.js.yml'
      - 'src/**'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/node.js.yml'
      - 'src/**'
      - 'Dockerfile'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/docker-build.yml@5235495a509bd8c8b37a7642c575e5074ea2d2d0
